# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c79a85bc6c9a67d9c8363bca779af1e60aa936b83e74e8f973a473d8aa55f34d631c182abedd0197f6579304ae2238cb0c8861633b6529ddd2dcd0c817d4927

test:
  secret_key_base: 53d67516767c1fcc911fa13f3f08f0482a863b0141138c87214d402b75f16960a9b88d2dff5140548550a22a7e6bf0125be869ef75459b34ab37f09addd62161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
